// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace SUP_INV1_0
{
    public partial class DemandPred
    {
        /// <summary>
        /// model input class for DemandPred.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"RecID")]
            public int RecID { get; set; }
            [LoadColumn(1)]
            [ColumnName(@"ItemID")]
            public int ItemID { get; set; }
            [LoadColumn(3)]
            [ColumnName(@"Category")]
            public int Category { get; set; }
            [LoadColumn(4)]
            [ColumnName(@"RecSoldAmountQuantity")]
            public float RecSoldAmountQuantity { get; set; }
            [LoadColumn(8)]
            [ColumnName(@"RecDateSold")]
            public float RecDateSold { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DemandPred.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"RecSoldAmountQuantity")]
            public float[] RecSoldAmountQuantity { get; set; }

            [ColumnName(@"RecSoldAmountQuantity_LB")]
            public float[] RecSoldAmountQuantity_LB { get; set; }

            [ColumnName(@"RecSoldAmountQuantity_UB")]
            public float[] RecSoldAmountQuantity_UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"C:\Users\user\source\repos\SUP-INV1.0\SUP-INV1.0\DemandPred.mlnet");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

